[REFACTOR]
SeSAC-Haul/DoToli-backend pull request #22
Opened 2024-10-16 07:30 UTC by liimjiin

## 관련 이슈

- Closes #21 

## 변경 사항

1. `MyPageController` 생성
   - `TaskController`의 마이페이지 관련 로직을 분리하여 `MyPageController`로 이동
   - 사용자 마이페이지 정보를 조회하는 `/api/mypage` 엔드포인트 생성
2. `MyPageService` 생성
   - `TaskService`의 마이페이지 관련 메서드를 분리하여 `MyPageService`로 이동
   - `calculateCompletionRate`메서드 접근 제한자 `public` -> `private` 변경
3. `TaskController`, `TaskService` 수정
   - 마이페이지 관련 로직 삭제
   - `MyPageResponseDto` import 삭제

## 스크린샷

`MyPage 조회 기능`
|변경 전|변경 후 |
|---|---|
|`TaskController`에서 마이페이지 조회|`MyPageController`에서 마이페이지 조회|
## 체크리스트

- [ ] 코드 컨벤션을 준수하였습니까?
- [ ] 모든 테스트를 통과하였습니까?
- [ ] 관련 문서를 업데이트하였습니까?

## 공유사항

- MyPageController를 생성하여 마이페이지 엔드포인트를 분리했습니다.
- TaskController와 TaskService에서 마이페이지 관련 로직을 분리하고 테스트까지 진행 완료했습니다. 

## 추후 업무

- [ ] 마이페이지 추가 기능 논의 및 개발

2024-10-16 11:14 UTC, Chan-GN requested changes
전반적으로 적절하게 리팩토링을 잘해주신 것 같습니다. 고생 많으셨어요.
다만 몇 가지 수정하면 좋을 것 같은 부분이 보여 리뷰를 남깁니다.
각 라인에 남긴 리뷰를 참고하셔서 리팩토링을 다시 진행해보시면 좋겠습니다.

2024-10-16 11:14 UTC, Chan-GN commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +	private Long calculateCompletionRate(Long memberId) {
이 메서드는 불필요한 중복 쿼리를 포함하고 있습니다. 매개변수를 변경하여 중복 쿼리를 제거해보세요.

2024-10-16 11:14 UTC, Chan-GN commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +	public Long getTotalTaskCountForMember(Long memberId) {
단순 조회 메서드를 메서드로 추출하는 것에 대해 좀 더 고민해보시면 좋겠습니다.

2024-10-16 11:14 UTC, Chan-GN commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +		return new MyPageResponseDto(member.getEmail(), member.getNickname(), totalTasks, completedTasks,
여기서 Member 엔터티에 대해 불필요한 쿼리가 발생하지 않는지 확인하시면 좋을 것 같습니다.
만약 Member 엔티티에 대해 쿼리가 발생한다면 컨트롤러 레이어의 userDetails의 Member 정보를 바로 사용하는 것을 고려해보세요.

2024-10-16 11:14 UTC, Chan-GN commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +		Long totalTasks = getTotalTaskCountForMember(memberId);
변수명을 totalTaskCount와 같이 변경하는 것을 고려해보세요.

2024-10-16 15:01 UTC, hyerin315 approved these changes
리팩토링까지 고생 많으셨습니다!

2024-10-16 15:01 UTC, hyerin315 commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +		Long totalTasks = getTotalTaskCountForMember(memberId);
찬근님 의견에 동감합니다. 
변수명을 메서드명과 같은 방향으로 Count까지 포함하는 게 직관적일 것 같기도 하네요.

2024-10-17 07:12 UTC, liimjiin commented on src/main/java/org/example/dotoli/service/MyPageService.java
> +		Long totalTasks = getTotalTaskCountForMember(memberId);
리뷰 감사드립니다! 말씀하신 부분 수정하겠습니다 :D

2024-10-17 10:48 UTC, Chan-GN approved these changes
중복 및 불필요한 쿼리를 적절하게 잘 제거하신 것 같습니다.
변수명도 잘 변경해주셔서 어떤 역할을 수행하는 메서드인지 보다 쉽게 파악할 수 있었습니다.
고생 많으셨습니다!

2024-10-17 11:16 UTC, cuteJJong approved these changes
리팩토링까지 하시느라 고생많으셨습니다. 의도를 파악하기 쉽고 좋았습니다.

2024-10-17 14:56 UTC, merged